<a href="https://colab.research.google.com/github/Riturajseal2001/numpy-exercise/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
ar = np.zeros(10)

In [ ]:
print(ar.size)

10


In [ ]:
ar1 = np.zeros(10)
ar1[4] = 1
print(ar1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
V = V[:: -1 ]
print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
ar3 = np.arange(0,9)
ar3 = ar3.reshape(3,3)
print(ar3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


In [ ]:
ar = np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.random.uniform((3,3,3)))

[2.9806496  2.5923613  1.66480581]


In [ ]:
ar = np.random.random((10,10))
mn = ar.min()
mx = ar.max()
print(ar)
print(mn)
print(mx)

[[0.16096837 0.53568309 0.0422346  0.87623425 0.17748971 0.04004316
  0.2169116  0.91515125 0.70810166 0.32815264]
 [0.49826799 0.55276244 0.94603032 0.54050616 0.28837058 0.93045859
  0.43290514 0.74106146 0.68439378 0.1602329 ]
 [0.21587385 0.4738481  0.89804214 0.63649939 0.31981579 0.20171828
  0.40268043 0.0852356  0.25158234 0.40135498]
 [0.32298287 0.73280403 0.7423344  0.73445049 0.32202678 0.41598925
  0.40221141 0.44698588 0.13537773 0.46579772]
 [0.42748519 0.73348677 0.43956696 0.64046916 0.1522644  0.85385522
  0.39409716 0.8181524  0.77967294 0.47204759]
 [0.86916128 0.11201117 0.1092997  0.51404854 0.91281055 0.16669753
  0.29619987 0.60394058 0.77256312 0.39892511]
 [0.49001248 0.93786093 0.46491872 0.06231716 0.2108306  0.47945718
  0.68915129 0.53515432 0.06488008 0.87437198]
 [0.27679403 0.31014526 0.16496692 0.47547632 0.54187197 0.29039815
  0.97376892 0.15437775 0.14392064 0.82595026]
 [0.15872656 0.75344358 0.48918558 0.44440521 0.30865188 0.28041512
  0.76590774

In [ ]:
v = np.random.random(30)
print(v.mean())
print(v)

0.4499368333986534
[0.56841821 0.38640011 0.78445216 0.88988495 0.54905746 0.12287011
 0.01381007 0.87844978 0.12825815 0.84816104 0.17367331 0.17716212
 0.51613066 0.06977962 0.22061955 0.32952713 0.81010879 0.16139781
 0.4875397  0.48605242 0.12943164 0.93567382 0.66903259 0.95435148
 0.21951462 0.03233365 0.19954912 0.71368805 0.079777   0.96299988]


In [ ]:
ar = np.ones((10,10))
ar[1:-1,1:-1] = 0
print(ar)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [ ]:
ar = np.diag(1+np.arange(4), k = -1)
print(ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
ar = np.zeros ((8,8))
ar[1::2, ::2]= 1
ar[::2, 1::2] = 1
print (ar)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
ar = np.random.random((5,5))
max, min = ar.max(), ar.min()
ar = (ar-min)/(max-min)
print (ar)

[[0.3693993  0.07772961 0.80365498 0.92101239 0.36557973]
 [0.01066449 0.54934019 0.21516429 0.66479042 0.17554274]
 [0.46118526 0.35714763 1.         0.97568951 0.57515698]
 [0.14658663 0.19579383 0.90024583 0.69629365 0.51804837]
 [0.26715433 0.8986345  0.17171475 0.1643597  0.        ]]


In [ ]:
color = np.dtype([("r", np.int),
                  ("g", np.int),
                  ("b", np.int),
                  ("a", np.int)])

In [ ]:
np.dot((np.arange(15).reshape((5,3))),(np.arange(6).reshape((3,2))))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [ ]:
x = np.arange(20)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
Z = np.arange(5)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([0., 1., 2., 3., 4.])

In [ ]:
ar = np.zeros(5)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 2., -5., -7., -8., -2., 10.,  3.,  9., -3., -5.])

In [ ]:
x = np.arange(0, 15)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
defaults = np.seterr(all="ignore")
# _ = np.seterr(**defaults)
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

In [62]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [70]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)
print(today)
print(yesterday)

2021-09-03
2021-09-02
2021-09-01
