<a href="https://colab.research.google.com/github/Riturajseal2001/numpy-exercise/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [2]:
ar = np.zeros(10)

In [3]:
print(ar.size)

10


In [4]:
ar1 = np.zeros(10)
ar1[4] = 1
print(ar1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
V = V[:: -1 ]
print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
ar3 = np.arange(0,9)
ar3 = ar3.reshape(3,3)
print(ar3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


In [9]:
ar = np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(np.random.uniform((3,3,3)))

[2.34735212 1.95726224 2.69445936]


In [11]:
ar = np.random.random((10,10))
mn = ar.min()
mx = ar.max()
print(ar)
print(mn)
print(mx)

[[0.20075091 0.26016945 0.4981646  0.90725003 0.29943476 0.97055196
  0.56195649 0.32168216 0.82071884 0.75549615]
 [0.66837728 0.14328212 0.64151249 0.03580336 0.35275633 0.81281909
  0.6110934  0.41971346 0.68297377 0.44724576]
 [0.74739722 0.06273339 0.10837827 0.99995568 0.56079291 0.53136931
  0.21181674 0.24533075 0.37915049 0.00983212]
 [0.70370597 0.27740669 0.94484042 0.44842081 0.29990011 0.967824
  0.15689054 0.20955374 0.39360323 0.64648183]
 [0.77047765 0.27975294 0.14156542 0.60142954 0.8406322  0.40491707
  0.58849645 0.27181061 0.45630364 0.51700815]
 [0.74506706 0.10979531 0.22739624 0.69442725 0.89232243 0.37851716
  0.24077266 0.38612835 0.08566642 0.94606197]
 [0.66984402 0.78361081 0.76847841 0.20092728 0.93378856 0.08712303
  0.50156944 0.88315992 0.87589777 0.78889455]
 [0.09037246 0.50108438 0.71486798 0.9178648  0.19197073 0.73527763
  0.69905674 0.92100643 0.02253343 0.24866999]
 [0.64503316 0.39474256 0.08760539 0.34795199 0.60669698 0.22154253
  0.21042079 0

In [12]:
v = np.random.random(30)
print(v.mean())
print(v)

0.4811549351700417
[0.50086876 0.36326007 0.31876635 0.44442864 0.86781412 0.04272695
 0.38853577 0.1780626  0.44317262 0.22831161 0.36392222 0.67094103
 0.79702203 0.72202961 0.04556648 0.18178042 0.17439634 0.45949695
 0.88406417 0.50571584 0.68705666 0.31923945 0.16553681 0.7868126
 0.4917836  0.45012758 0.6671768  0.43479272 0.89189131 0.95934793]


In [13]:
ar = np.ones((10,10))
ar[1:-1,1:-1] = 0
print(ar)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [15]:
ar = np.diag(1+np.arange(4), k = -1)
print(ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
ar = np.zeros ((8,8))
ar[1::2, ::2]= 1
ar[::2, 1::2] = 1
print (ar)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [17]:
ar = np.random.random((5,5))
max, min = ar.max(), ar.min()
ar = (ar-min)/(max-min)
print (ar)

[[0.82404858 0.75404303 0.45243579 0.61930479 0.44834281]
 [0.28995846 0.73996437 1.         0.02638477 0.39008332]
 [0.80571797 0.57042255 0.12409931 0.5671532  0.61788548]
 [0.35867273 0.83363071 0.60342968 0.2397616  0.74142224]
 [0.01817088 0.04601159 0.67552322 0.         0.17368009]]


In [18]:
color = np.dtype([("r", np.int),
                  ("g", np.int),
                  ("b", np.int),
                  ("a", np.int)])

In [19]:
np.dot((np.arange(15).reshape((5,3))),(np.arange(6).reshape((3,2))))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [20]:
x = np.arange(20)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [22]:
Z = np.arange(5)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([0., 1., 2., 3., 4.])

In [23]:
ar = np.zeros(5)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [24]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-9., 10.,  9.,  4., -4.,  4.,  6., -7.,  3., -1.])

In [25]:
x = np.arange(0, 15)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
defaults = np.seterr(all="ignore")
# _ = np.seterr(**defaults)
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

In [27]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [28]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)
print(today)
print(yesterday)

2021-09-13
2021-09-12
2021-09-11
